// PRODUCT
export const GET_PRODUCTS = "GET_PRODUCTS"
export const SAVE_PRODUCTS = "SAVE_PRODUCTS"
export const GET_PRODUCTS_IN_CATEGORY = "GET_PRODUCTS_IN_CATEGORY"
export const CLEAR_PRODUCTS_IN_CATEGORY = "CLEAR_PRODUCTS_IN_CATEGORY"
export const GET_PRODUCT = "GET_PRODUCT"
export const ADD_SAVED_ITEM = "ADD_SAVED_ITEM"
export const REMOVE_SAVED_ITEM = "REMOVE_SAVED_ITEM"
// CART
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const DECREASE_PRODUCT_QUANTITY = "DECREASE_PRODUCT_QUANTITY"
export const EMPTY_CART = "EMPTY_CART"

// AUTH
export const SIGN_IN_WITH_GOOGLE = "SIGN_IN_WITH_GOOGLE"
export const SET_AUTH_STATUS = "SET_AUTH_STATUS"
export const SET_USER = "SET_USER"
export const SIGN_OUT = "SIGN_OUT"